version: '3.8'

services:
  discovery-service:
    image: sivasankaran476/serviceregistry:latest
    container_name: discovery-service
    ports:
      - "8761:8761"
    depends_on:
      - zipkin
    networks:
      - ecom-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  api-gateway:
    image: sivasankaran476/apigateway:latest
    container_name: api-gateway
    depends_on:
      - discovery-service
    ports:
      - "8765:8765"
    networks:
      - ecom-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/

  security-service:
    image: sivasankaran476/security:latest
    container_name: security-service
    depends_on:
      - zipkin
      - discovery-service
    ports:
      - "8989:8989"
    networks:
      - ecom-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/

  product-service:
    image: sivasankaran476/product:latest
    container_name: product-service
    ports:
      - "8090:8090"
    depends_on:
      - zipkin
      - discovery-service
      - api-gateway
      - security-service
    networks:
      - ecom-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      
  notification-service:
    image: sivasankaran476/notification:latest
    container_name: notification-service
    ports:
      - "9090:9090"
    depends_on:
      - zipkin
      - discovery-service
      - api-gateway
      - security-service
    networks:
      - ecom-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - ecom-network

networks:
  ecom-network:
    driver: bridge
